# Generated by Django 3.2.5 on 2021-07-11 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surface',
            fields=[
                ('id', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=500)),
                ('condition', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('number', models.IntegerField(max_length=50)),
                ('width', models.IntegerField(max_length=100)),
                ('length', models.IntegerField(max_length=100)),
                ('Surface', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='airport.surface')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('runway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.runway')),
            ],
        ),
    ]
